import = []

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[colors]

[colors.primary]
background = '#0a0a13'
foreground = '#a9b1d6'

[colors.normal]
black = '#32344a'
red = '#f7768e'
green = '#26a269'
yellow = '#e0af68'
blue = '#12488b'
magenta = '#ad8ee6'
cyan = '#449dab'
white = '#9699a8'

[colors.bright]
black = '#444b6a'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'
